import { getSiteUrl } from '@/lib/site';

// Every real, indexable page. The template demo pages (see
// lib/noindex-routes.js) and redirect sources are deliberately absent.
// When you add a page, add it here.
const ROUTES = [
  '/',
  '/about',
  '/about/founder',
  '/about/team',
  '/alfred',
  '/contact',
  '/intake',
  '/news',
  '/news/blog',
  '/news/blog/business-value',
  '/news/blog/ja-youth-summit-why-we-showed-up',
  '/news/blog/motta-preparing-for-your-cpas-retirement',
  '/news/blog/motta-scorp-designation-5-strategic-reasons',
  '/news/blog/paying-it-forward-suffolk-scholarship',
  '/news/blog/real-tea-podcast-with-nicole-hartick',
  '/news/blog/tax-impact-of-federal-student-aid',
  '/news/blog/tax-policy-crossroads',
  '/news/blog/taxes-for-real-estate-professionals',
  '/news/blog/team-up-for-your-success',
  '/news/blog/types-of-rental-properties',
  '/news/blog/why-your-rental-property-belongs-in-an-llc',
  '/news/community',
  '/news/community/ja-southern-massachusetts',
  '/news/community/suffolk-seed',
  '/news/media',
  '/news/press',
  '/news/press/ja-youth-summit-2026',
  '/news/press/proconnect-case-study',
  '/partnerships',
  '/partnerships/financial-advisors',
  '/partnerships/suffolk-seed',
  '/partnerships/white-label',
  '/resources',
  '/services',
  '/services/accounting',
  '/services/accounting-advisory',
  '/services/accounting/bookkeeping',
  '/services/accounting/business-infrastructure',
  '/services/accounting/cfo-controller',
  '/services/accounting/financial-reporting',
  '/services/accounting/forensic-accounting',
  '/services/accounting/order-to-cash',
  '/services/accounting/payroll',
  '/services/accounting/procure-to-pay',
  '/services/accounting/record-to-report',
  '/services/business-advisory',
  '/services/business-ai-transformation',
  '/services/business-entity-structuring',
  '/services/financial-planning',
  '/services/financial-statement-analysis',
  '/services/ma',
  '/services/ma/business-valuations',
  '/services/ma/buy-sell-advisory',
  '/services/ma/due-diligence',
  '/services/ma/financial-modeling',
  '/services/ma/integration',
  '/services/ma/quality-of-earnings',
  '/services/management-consulting',
  '/services/saas-tech-advisory',
  '/services/tax',
  '/services/tax/s-corp',
  '/services/tax/small-business',
  '/services/wealth-management',
];

export default function sitemap() {
  const site = getSiteUrl();
  return ROUTES.map((path) => ({
    url: path === '/' ? site : site + path,
    changeFrequency: 'monthly',
    priority: path === '/' ? 1 : 0.7,
  }));
}
